config/routes.rb
  Blog::Application.routes.draw do
  resources :posts

  devise_for :users

  devise_for :mode_lrails
    root :to => "welcome#index"
  end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
     # guest user (not logged in
    if user.id == 1 
     can :manage, :all
    else
      can :read, :all
      can :update, Post, :user_id=>user.id
      can :show, Post, :user_id=>user.id
      can :destroy, Post, :user_id=>user.id
      can :create, Post, :user_id=>user.id
      can :edit, Post, :user_id=>user.id

    end

  end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
end

app/models/mode_lrail.rb
class ModeLrail < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email,
                  :password,
                  :password_confirmation,
                  :remember_me,
                  :name,
                  :surname
  # attr_accessible :title, :body
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :text, :title, :name, :user_id
  belongs_to :user

  validates :title, :presence => true,
            :length => { :minimum => 5 }
end

app/models/role.rb
class Role < ActiveRecord::Base
 attr_accessible :name
  has_many :users_roles
  has_many :users, :through => :users_roles
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email,
                  :password,
                  :password_confirmation,
                  :remember_me,
                  :admin,
                  :name,
                  :surname,
                  :user_id

  has_many :posts 
  has_many :users_roles
  has_many :roles, :through => :users_roles
  before_create :create_role
  private

  def create_role
    self.roles << Role.find_by_name(:user)
  end

end

app/models/users_role.rb
class UsersRole < ActiveRecord::Base
  attr_accessible :role_id

  belongs_to :user
  belongs_to :role
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from CanCan::AccessDenied do |exception|
    flash[:error] = "Access denied."
    redirect_to root_url
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, :only => :show
  load_and_authorize_resource
  skip_authorize_resource :only => :show
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(params[:post])
    
    @post.update_attributes(:user_id=>current_user.id)
    if @post.save
      redirect_to :action => :show, :id => @post.id
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def index
    @posts = Post.all
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update_attributes(params[:post])
      redirect_to :action => :show, :id => @post.id
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to :action=> :index
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
 #   :admin
  end

#  -----
  def resource
    @resource ||= User.new
 #   @resource ||= Admin.new
  end


  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blooog^_^</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
    <body>
    <div class="navbar">
      <div class="navbar-inner">
        <div class="row">
        <div class="span5 offset2">
        <div class="nav">
          <li><a href="/#"><i class="icon-home"><p class="text-info">Home</p></i></a></li><li class="divider-vertical"></li>
          <li><a href="/posts"><i class="icon-list-alt"><p class="text-info">Listing posts</p></i></a></li><li class="divider-vertical"></li>
          <li><a href="/posts/new"><i class="icon-pencil"><p class="text-info">Create new post</p></i></a></li><li class="divider-vertical"></li>
        </div>
        </div>
        <div class="span3 offset2">

            <%= render "shared/links" %>

        </div>
      </div>
          </div>
    </div>

        <div class="container">
        </div>
        </div>
    <% if notice %>
        <p class="alert alert-notice"><%= notice %></p>
    <% end %>
    <% if alert %>
        <p class="alert alert-error"><%= alert %></p>
    <% end %>

    <%= yield %>
        </div>
    </body>
</html>

app/views/posts/_form.html.erb
<div class="row">
<%= form_for @post do |f| %>
    <% if @post.errors.any? %>
        <div id="errorExplanation">
          <div class="alert-error"><h6><%= pluralize(@post.errors.count, "error") %> prohibited
            this post from being saved:</h6>
          </div>
          <ul>
            <% @post.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
      <p>
        <%= f.label :title %>
         <%= f.text_field :title %>
      </p>

      <p>
        <%= f.label :text %><br>
        <textarea rows="4"<%= f.text_area :text %></textarea>
      </p>
      </div>
      <%=f.submit  "Save", :class=>"btn btn-primary"%>
<% end %>

app/views/posts/edit.html.erb
<div class="row">
  <div class="span3 offset5">
    <h1>Edit post</h1>
    <%= render 'form' %>
      <%= link_to 'Back',posts_path, :action => :index, :class=>"btn btn-primary" %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="row">
  <div class="span3 offset5">
    <h1>Listing posts</h1>
  </div>

</div>
<div class="row-fluid">
<% @posts.each do |post| %>

<div class="row-fluid">
  <div class="span2 offset4">
    <h5><%= Post.find(post.id).user.name %> <%= Post.find(post.id).user.surname %></h5>
    <h3><%= post.title  %></h3>
  </div>
    <div class="span3">
        <div class="btn-group">
          <% if can? :read, Post %>
          <%= link_to 'Show',post_path(post), :action => :show, :id => post.id, :class=>"btn btn-primary"%>
          <% end %>
          <% if post.user_id == current_user.id %>
          <%= link_to 'Edit',edit_post_path(post), :action => :edit, :id => post.id,  :class=>"btn btn-primary"%>
          <% end %>
          <% if post.user_id == current_user.id%>
              <%= link_to 'Destroy', { :action => :destroy, :id =>post.id}, :method => :delete, :confirm => 'Are you sure?', :class=>"btn btn-primary" %>
          <% end %>
        </div>
    </div>
</div>

<div class="row-fluid">
    <div class="span5 offset4">
        <pre>
     <%= post.text %>
        </pre>
    </div>
</div>
<% end %>
</div>

app/views/posts/new.html.erb
<div class="row">
  <div class="span3 offset5">
    <h1>New post</h1>
    <%= render 'form' %>

    <%=  link_to 'Back', posts_path, :class=>"btn btn-primary" %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="row" xmlns="http://www.w3.org/1999/html">
    <div class="span3 offset5">
  <h1><%= @post.title %></h1>
    </div>
</div>

<p>
  <div class="row">
    <div class="span3 offset5">
      <pre>
      <%= @post.text %>
      </pre>
    </div>
  </div>
</p>
<div class="span3 offset5">
<div class="btm-proup">

    <%= link_to 'Back', posts_path, :action => :index, :class=>"btn btn-primary" %>
    
      </div>
</div>

app/views/shared/_links.html.erb
<ul>
  <% if user_signed_in? %>
      <p class="text-success">Здравствуйте, <%= current_user.email %></p>
      <li><%= link_to "My Profile", edit_user_registration_path%> </li>
      <li><%= link_to "Sign out", destroy_user_session_path%> </li>
  <% else %>
      <li><%= link_to "Sign up", new_user_registration_path%> </li>
      <li><%= link_to "Sign in", new_user_session_path%> </li>
  <% end %>
</ul>

app/views/welcome/index.html.erb
<div class="raw">
  <div class="span 4 offset4">
    <h1>Hello ! Welcome to my blog</h1>
        <div class="btn btn-large">
            <%= link_to "My Blog", :controller => "posts" %>
        </div>
  </p>
    <div class="raw">
      <%= link_to image_tag("ru9gag.gif",:width =>250, :height => 300) %>
    </div>
    </p>
    </div>
</div>